services:
  fc-services:
    container_name: fc-services
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/fc-services/src
    ports:
      - "5000:5000"
    environment:
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      SECRET: ${SECRET}
      PORT: ${PORT}
  fc-web:
    container_name: fc-web
    command: npm run dev
    volumes:
      - ./front-end:/fc-web
    ports:
      - "3000:3000"
    build:
      context: front-end-bkp
  fc-mongo:
    image: mongo:7.0
    container_name: fc-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/fc-mongo/data:/data/db
      - ./docker/fc-mongo/seed.js:/docker-entrypoint-initdb.d/seed.js
      - /etc/localtime:/etc/localtime:ro
