version: '3.8'

services:
  fc-web:
    container_name: fc-web
    build:
      context: ./src/web
      dockerfile: Dockerfile
    volumes:
      - ./src/web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - fc-core
    environment:
      - NEXT_PUBLIC_API_URL=http://fc-core:5000

  fc-core:
    container_name: fc-core
    build:
      context: ./src/core
      dockerfile: Dockerfile
    volumes:
      - ./src/core:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: npm run dev
    depends_on:
      - fc-mongo
    environment:
      - MONGODB_URI=mongodb://fc-mongo:27017/finance-control
      - JWT_SECRET=${JWT_SECRET:-supersecretdev}
      - PORT=5000
      - NODE_ENV=development

  fc-mongo:
    container_name: fc-mongo
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/fc-mongo/data:/data/db
      - /etc/localtime:/etc/localtime:ro
